import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from 'next-themes'
import Footer from "./components/Footer";
import Header from "./components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "coffee house+",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
      
      <body className={inter.className}>
          <header>
          <Header/>
          </header>
    <main>
    {children}
    </main>
        
        <Footer/>
        </body>
     
    </html>
  );
}
